baseURL: https://dhrubokarmaker.netlify.app
languageCode: en-us
title:  Dhrubo Karmaker
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Dhrubo Karmaker'r portfolio
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: ""
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false


  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "Web/icons8-google-code-windows-10-32.png"
    favicon16x16: "Web/icons8-google-code-windows-10-16.png"
    favicon32x32: "Web/icons8-google-code-windows-10-32.png"
    apple_touch_icon: "macOS/icons8-google-code-windows-10-32.svg"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Dhrubo Karmaker
    subtitle: "Computer Science & Statistcs @ UBC"
    imageUrl: "dp.jpg"
    imageWidth: 600
    imageHeight: 600
    imageTitle: my image
    buttons:
      - name: Resume
        url: "DhruboKarmakerFullStackResume.pdf"

  # home-info mode
  homeInfoParams:
    Title: "Dhrubo Karmaker"
    Content: Computer Science and Statistics @UBC, Year 3
    imageUrl: "dp.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/dhrubokarmaker"
    - name: email
      url: "mailto:dhruv.karmaker@gmail.com"
    - name: github
      url: "https://github.com/dhrubokarmaker"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content","tech"]
menu:
  main:
    - identifier: resume
      name: resume
      url: ./DhruboKarmakerFullStackResume.pdf
      weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 20
   
    - identifier: about
      name: about
      url: /about/
      weight: 30
    

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
